### ISSUE TITLE
Share a non-docker volume

### ISSUE THREAD

**Issue by maxiride** [gdiepen/volume-sharer#7]
I'd like to use this image to also share local folders on the docker host.
How could one proceed to do so?

I've tried to bind mount a local path to a submount in `/docker_volumes` with no success.

`docker run --name volume-sharer --rm -v /var/lib/docker/volumes:/docker_volumes -v /home/myName/test:/docker_volumes/uniqueNameTest -p 139:139 -p 445:445 -v /var/run/docker.sock:/var/run/docker.sock -d gdiepen/volume-sharer`

**Comment by gdiepen** [comment]
You would need to ensure that these extra mounts would also be added to the underlying smb.conf.

If I understand your question correctly, you would need to modify the create_volume_shares bash function

**Comment by maxiride** [comment]
Thanks for the hint, I suppose I could jus fire up another container with the base image dperson/samba and get away with its sharing capabilities.

**Comment by gdiepen** [comment]
When starting a second container, just have to think about the ports, you cannot have two containers bind to the same ports that are needed for samba to work
